import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto = Noto_Sans_KR({
  display: "block",
  variable: "--font-noto",
  preload: false,
});

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html className="w-full h-full" lang="en">
    <body
      className={`relative flex flex-col h-full w-full overflow-auto ${noto.className}`}
    >
      <header className="flex flex-col gap-4 p-5 h-32">
        <h1 className="w-full flex flex-col items-center text-4xl font-bold text-chacol whitespace-nowrap animate-fontLoop">
          contextyler
        </h1>
        <p className="text text-center text-test whitespace-pre-wrap">
          {`글의 문맥을 분석해 어울리는 폰트 스타일을 추천합니다.`}
        </p>
      </header>
      <main className="overflow-auto w-full h-full leading-6">{children}</main>
    </body>
  </html>
);

export default RootLayout;
